#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 手动加载 nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Tests are not run at push time since they can take 2-4 minutes to complete
npm run format-check
npm run lint
